#!/usr/bin/env bash

# Description: Search code with fzf

FOLDER=${PWD:-$1}

rg --line-number --no-heading '' "$FOLDER" |
fzf --delimiter ':' --preview 'bat --style=numbers --color=always {1} --highlight-line {2}'
