#!/usr/bin/env bash

# Description: Search code with fzf
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source $SCRIPT_DIR/tools/qol-preamble --rg-verify --fzf-verify

FOLDER=${PWD:-$1}

rg --line-number --no-heading '' "$FOLDER" |
fzf --delimiter ':' --preview 'bat --style=numbers --color=always {1} --highlight-line {2}'
