#!/usr/bin/env bash
# Emoji picker using fzf
# Description: Search for emojis and copy them to your clipboard

# Determine the tone to use. Command line argument takes precedence over environment variable.
if [[ -n "$1" && "$1" == --* ]]; then
    INPUT_TONE="${1#--}"
else
    INPUT_TONE="${QOL_EMOJI_SKIN_TONE}"
fi
MULTI_TONE=false
case "$INPUT_TONE" in
    light)
        TONE1=$'\U1F3FB'
        TONE2=$'\U1F3FC'
        TONE3=$'\U1F3FD'
        TONE4=$'\U1F3FE'
        TONE5=$'\U1F3FF'
        MULTI_TONE=true
        ;;
    medium-light)
        TONE1=$'\U1F3FC'
        TONE2=$'\U1F3FD'
        TONE3=$'\U1F3FE'
        TONE4=$'\U1F3FF'
        TONE5=$'\U1F3FB'
        MULTI_TONE=true
        ;;
    medium)
        TONE1=$'\U1F3FD'
        TONE2=$'\U1F3FE'
        TONE3=$'\U1F3FF'
        TONE4=$'\U1F3FB'
        TONE5=$'\U1F3FC'
        MULTI_TONE=true
        ;;
    medium-dark)
        TONE1=$'\U1F3FE'
        TONE2=$'\U1F3FF'
        TONE3=$'\U1F3FB'
        TONE4=$'\U1F3FC'
        TONE5=$'\U1F3FD'
        MULTI_TONE=true
        ;;
    dark)
        TONE1=$'\U1F3FF'
        TONE2=$'\U1F3FB'
        TONE3=$'\U1F3FC'
        TONE4=$'\U1F3FD'
        TONE5=$'\U1F3FE'
        MULTI_TONE=true
        ;;
    *)
        TONE1=""
        MULTI_TONE=false
        ;;
esac

# ----------------------------------------------------------------------
# 1. Emoji list
# ----------------------------------------------------------------------
# Each line: <emoji><tab><description>
read -r -d '' EMOJI_DATA <<'EOF'
😀	grinning face
😃	grinning face with big eyes
😄	grinning face with smiling eyes
😁	beaming face with smiling eyes
😆	grinning squinting face
😅	grinning face with sweat
🤣	rolling on the floor laughing
😂	face with tears of joy
🙂	slightly smiling face
🙃	upside‑down face
😉	winking face
😊	smiling face with smiling eyes
🥰	smiling face with hearts
😍	heart‑eyes
🤩	star‑struck
😘	face blowing a kiss
😗	kissing face
😚	kissing face with closed eyes
😙	kissing face with smiling eyes
🤗	hugging face
🤔	thinking face
🤨	face with raised eyebrow
🧐	face with monocle
🤓	nerd face
😎	sunglasses
🥳	party face
😏	sly smile
😒	unamused
😞	disappointed
😔	pensive
😟	worried
😕	confused
🙁	frowning
☹️	frowning face
😣	persevering
😖	confounded
😫	tired face
😩	weary
🥺	pleading face
😢	crying face
😭	loudly crying
😤	face with steam from nose
😠	angry
🤬	cursing face
🤯	exploding head
😱	screaming in fear
😨	fearful
😰	anxious with sweat
😥	downcast face with sweat
🤗	hugging
🤔	thinking
🤭	face with hand over mouth
🤫	shushing face
🤥	lying face
🤢	nauseated
🤮	vomiting
🤧	sneezing
🥵	hot face
🥶	cold face
🥴	woozy face
😵	dizzy face
🤐	zipper‑mouth face
🤑	money‑mouth
🤠	cowboy hat face
🤡	clown face
👻	ghost
💀	skull
☠️	skull and crossbones
👽	extraterrestrial
🤖	robot
🎃	jack‑o‑lantern
😺	grinning cat
😸	grinning cat with smiling eyes
😹	cat with tears of joy
😻	heart‑eyes cat
😼	cat with wry smile
😽	kissing cat
🙈	see‑no‑evil monkey
🙉	hear‑no‑evil monkey
🙊	speak‑no‑evil monkey
👶	people: baby
🧒	people: child
👦	people: boy
👧	people: girl
🧑	people: person
👱	people: person with blond hair
👨	people: man
🧔	people: person with beard
🧔‍♂️	people: man with beard
🧔‍♀️	people: woman with beard
👨‍🦰	people: man with red hair redhead
👨‍🦱	people: man with curly hair
👨‍🦳	people: man with white hair
👨‍🦲	people: bald man
👩	people: woman
👩‍🦰	people: woman with red hair redhead
🧑‍🦰	people: person with red hair redhead
👩‍🦱	people: woman with curly hair
🧑‍🦱	people: person with curly hair
👩‍🦳	people: woman with white hair
🧑‍🦳	people: person with white hair
👩‍🦲	people: bald woman
🧑‍🦲	people: bald person
👱‍♀️	people: woman blond hair
👱‍♂️	people: man blond hair
🧓	people: older person elder
👴	people: old man elder
👵	people: old woman elder
🧏	people: deaf person
🧏‍♂️	people: deaf man
🧏‍♀️	people: deaf woman
👳	people: person wearing turban
👳‍♂️	people: man wearing turban
👳‍♀️	people: woman wearing turban
👲	people: person with skullcap
🧕	people: woman with headscarf
🤰	people: pregnant woman
🫃	people: pregnant man
🫄	people: pregnant person
👼	people: baby angel
🗣️	speaking head
👤	bust in silhouette
👥	busts in silhouette
🫂	people hugging
🦰	red hair
🦱	curly hair
🦳	white hair
🦲	bald
🙍	people: person frowning
🙍‍♂️	people: man frowning
🙍‍♀️	people: woman frowning
🙎	people: person pouting
🙎‍♂️	people: man pouting
🙎‍♀️	people: woman pouting
🙅	people: person gesturing no
🙅‍♂️	people: man gesturing no
🙅‍♀️	people: woman gesturing no
🙆	people: person gesturing ok
🙆‍♂️	people: man gesturing ok
🙆‍♀️	people: woman gesturing ok
💁	people: person tipping hand
💁‍♀️	people: woman tipping hand
💁‍♂️	people: man tipping hand
🙋	people: person raising hand
🙋‍♂️	people: man raising hand
🙋‍♀️	people: woman raising hand
🙇	people: person bowing
🙇‍♂️	people: man bowing
🙇‍♀️	people: woman bowing
🤦	people: person facepalming
🤦‍♂️	people: man facepalming
🤦‍♀️	people: woman facepalming
🤷	people: person shrugging
🤷‍♂️	people: man shrugging
🤷‍♀️	people: woman shrugging
👍	hand: thumbs up
👎	hand: thumbs down
✊	hand: fist
🤞	hand: crossed fingers
🤟	hand: love‑you gesture
🤘	hand: sign of the horns
🤙	hand: call me hand
👏	hand: clapping hands
🙌	hand: raising hands
🤲	hand: palms up together
👐	hand: open hands
🤝	hand: handshake
💪	hand: flexed biceps
🖐	hand: hand with fingers splayed
✋	hand: raised hand
🤚	hand: raised back of hand
🖖	 hand: Vulcan/Spock salute
👋	hand: waving hand
✌️	hand: victory sign
🤏	hand: pinching hand
🤌	hand: pinched fingers
👌	hand: ok sign
🫸	hand: rightward pushing hand
🫷	hand: leftward pushing hand
🫴	hand: palm up hand
🫳	hand: palm down hand
🫲	hand: leftward facing hand
🫱	hand: rightward facing hand
🫵	hand: pointing at viewer
👊	hand: oncoming fist fistbump
🤛	hand: left-facing fist
🤜	hand: right-facing fist
🫶	hand: heart hands
🫰	hand: index finger and thumb crossed
👈	hand: index finger pointing left
👉	hand: index finger pointing right
👆	hand: index finger pointing up back
☝️	hand: index finger pointing up front
👇	hand: index finger pointing down
🖕	hand: middle finger extended the bird
🙏	hand: folded hands praying prayer
✍️	hand: writing hand
💅	hand: nail polish
🦵	leg
🦶	foot
👂	ear
🦻	ear with hearing aid
👃	nose
🤳	selfie
🦾	hand: hand on mechanical arm
🦿	mechanical leg
🧠	brain
🫀	anatomical heart
🫁	lungs
🦷	tooth
🦴	bone
👀	eyes
👁️	eye
👅	tongue
👄	mouth
🫦	biting lip
👣	footprints
🫆	fingerprint
🧬	DNA molecule
🩸	drop of blood
💍	ring
💎	diamond
📱	smartphone
💻	laptop
🖥	desktop computer
⌚	watch
📚	books
🗂	file folder
🧭	compass
🧰	toolbox
🧲	magnet
🧪	test tube
🧬	DNA
🧭	compass
🧱	brick
🧑‍💻	technologist
🧑‍🚀	astronaut
🧑‍⚕️	health worker
🧑‍🍳	chef
🧑‍🎓	student
🧑‍🎤	singer
🧑‍🏫	teacher
🧑‍🔧	mechanic
🧑‍🔬	scientist
🧑‍💼	office worker
🏃‍♂️	Male Runner
🏃‍♀️	Female Runner
🏃	Non-binary Runner
🚶‍♂️	Male Pedestrian
🚶‍♀️	Female Pedestrian
🚶	Non-binary Pedestrian
🚣‍♂️	Male Rower
🚣‍♀️	Female Rower
🚣	Non-binary Rower
🏊‍♂️	Male Swimmer
🏊‍♀️	Female Swimmer
🏊	Non-binary Swimmer
🏋️‍♂️	Male Weightlifter
🏋️‍♀️	Female Weightlifter
🏋️	Non-binary Weightlifter
🚴‍♂️	Male Cyclist on bike or bicycle
🚴‍♀️	Female Cyclist on bike or bicycle
🚴	Non-binary Cyclist on bike or bicycle
🚵‍♂️	Male Mountain Biker
🚵‍♀️	Female Mountain Biker
🚵	Non-binary Mountain Biker
🏇	Male Horse Racer
🏇	Female Horse Racer
🏇	Non-binary Horse Racer
🏌️‍♂️	Male Golfer
🏌️‍♀️	Female Golfer
🏌️	Non-binary Golfer
🏄‍♂️	Male Surfer
🏄‍♀️	Female Surfer
🏄	Non-binary Surfer
🤽‍♂️	Male Water Polo Player
🤽‍♀️	Female Water Polo Player
🤽	Non-binary Water Polo Player
🤾‍♂️	Male Handball Player
🤾‍♀️	Female Handball Player
🤾	Non-binary Handball Player
⛹️‍♂️	Male Basketball Player
⛹️‍♀️	Female Basketball Player
⛹️	Non-binary Basketball Player
🤺	Male Fencer
🤺	Female Fencer
🤺	Non-binary Fencer
🏂	Male Snowboarder
🏂	Female Snowboarder
🏂	Non-binary Snowboarder
⛷️	Male Skier
⛷️	Female Skier
⛷️	Non-binary Skier
🧗‍♂️	Male Climber
🧗‍♀️	Female Climber
🧗	Non-binary Climber
🧘‍♂️	Male Person in Lotus Position
🧘‍♀️	Female Person in Lotus Position
🧘	Non-binary Person in Lotus Position
🧖‍♂️	Male Person in Steamy Room
🧖‍♀️	Female Person in Steamy Room
🧖	Non-binary Person in Steamy Room
🕴️‍♂️	Male Businessperson Levitating
🕴️‍♀️	Female Businessperson Levitating
🕴️	Non-binary Businessperson Levitating
💃	Female Dancer
🕺	Male Dancer
🧑‍🎨	Non-binary Artist
👨‍🎨	Male Artist
👩‍🎨	Female Artist
🧑‍🎤	Non-binary Singer
👨‍🎤	Male Singer
👩‍🎤	Female Singer
👯‍♂️	Male People with Bunny Ears
👯‍♀️	Female People with Bunny Ears
👯	Non-binary People with Bunny Ears
🤹‍♂️	Male Juggler
🤹‍♀️ 	Female Juggler
🤹	Non-binary Juggler
🎭	Performing Arts
🩰	Ballet Shoes
🐶	Dog
🐱	Cat
🐭	Mouse
🐹	Hamster
🐰	Rabbit
🦊	Fox
🐻	Bear
🐼	Panda
🐨	Koala
🐯	Tiger (face)
🦁	Lion
🐮	Cow
🐷	Pig
🐽	Pig nose
🐸	Frog
🐵	Monkey
🐔	Chicken
🐧	Penguin
🐦	Bird
🐤	Baby chick
🐣	Hatching chick
🐥	Front‑facing chick
🦆	Duck
🦅	Eagle
🦉	Owl
🦇	Bat
🐺	Wolf
🐗	Boar
🐴	Horse
🦄	Unicorn
🐝	Bee
🐛	Bug
🦋	Butterfly
🐌	Snail
🐞	Lady beetle
🐜	Ant
🪰	Fly
🪱	Worm
🦟	Mosquito
🦗	Cricket
🐢	Turtle
🐍	Snake
🦎	Lizard
🐙	Octopus
🦑	Squid
🦐	Shrimp
🦞	Lobster
🦀	Crab
🐡	Blowfish
🐠	Tropical fish
🐟	Fish
🐬	Dolphin
🐳	Whale
🐋	Spouting whale
🦈	Shark
🐊	Crocodile
🐅	Tiger
🐆	Leopard
🦓	Zebra
🦍	Gorilla
🦧	Orangutan
🐘	Elephant
🦣	Mammoth
🦏	Rhinoceros
🦛	Hippopotamus
🐪	Camel
🐫	Two‑hump camel
🦒	Giraffe
🦘	Kangaroo
🦥	Sloth
🦦	Otter
🦨	Skunk
🦡	Badger
🐿️	Chipmunk
🦔	Hedgehog
🐾	Paw prints
🐉	Dragon
🐲	Dragon (face)
🦕	Sauropod
🦖	T‑rex
🫍	Orca killer whale blackfish
🫪	Distorted Face
🫯	Fight Cloud
🧑‍🩰	Ballet Dancer
🫈	Hairy Creature sasquatch yeti bigfoot
🪊	Trombone
🛘	Landslide
🪎	Treasure Chest
🐚	Spiral shell
🪸	Coral
🗺️	World map
🗾	Map of Japan
🧭	Compass
🏔️	Snow‑capped mountain
⛰️	Mountain
🏕️	Camping
🏖️	Beach with umbrella
🏜️	Desert
🏝️	Desert island
🏞️	National park
🏟️	Stadium
🏠	House
🏡	House with garden
🏢	Office building
🏣	Japanese post office
🏤	European post office
🏥	Hospital
🏦	Bank
🏨	Hotel
🏩	Love hotel
🏪	Convenience store
🏫	School
🏬	Department store
🏯	Japanese castle
🏰	European castle
🗽	Statue of Liberty
🗼	Tokyo tower
🗿	Moai statue
🛤️	Railway track
🛣️	Motorway
🛢️	Oil drum
🛳️	Passenger ship
⛴️	Ferry
🛥️	Motor boat
🚤	Speedboat
⛵	Sailboat
🚢	Ship
🛶	Canoe
🚁	Helicopter
✈️	Airplane
🛩️	Small airplane
🪂	Parachute
🚀	Rocket
🛰️	Satellite
🚂	Steam locomotive
🚆	Train
🚇	Metro
🚊	Tram
🚉	Station
🚞	Mountain railway
🚝	Monorail
🚟	Suspension railway
🚠	Mountain cableway
🚡	Aerial tramway
🛴	Kick scooter
🛹	Skateboard
🚲	Bicycle
🛵	Motor scooter
🏍️	Motorcycle
🚗	Car
🚙	SUV
🚕	Taxi
🚚	Delivery truck
🚛	Articulated lorry
🚜	Tractor
🛺	Auto rickshaw
🚦	Vertical traffic light
🚥	Horizontal traffic light
🛑	Stop sign
🏙️	Cityscape
🌆	Sunset over buildings
🌇	Sunrise over buildings
🌉	Bridge at night
🌁	Foggy bridge
🏛️	Classical building
🏗️	Building construction
🏚️	Derelict house
🏭	Factory
©️	Copyright
®️	Registered
™️	Trademark
℗️	Sound Recording Copyright
➕	Plus
➖	Minus
✖️	Multiply
➗	Divide
❓	Question Mark
❔	White Question Mark
❕	White Exclamation Mark
❗	Exclamation Mark
〰️	Wavy Dash
⚕️	Medical Symbol
♻️	Recycling Symbol
⚜️	Fleur-de-lis
🔱	Trident Emblem
📛	Name Badge
🔰	Japanese Symbol for Beginner
⭕	Hollow Red Circle
✅	Check Mark Button
☑️	Check Box with Check
❌	Cross Mark
❎	Cross Mark Button
〽️	Part Alternation Mark
⚠️	Warning
🚸	Children Crossing
⛔	No Entry
🚫	Prohibited
🔞	No One Under Eighteen
☢️	Radioactive
☣️	Biohazard
⬆️	Up Arrow
↗️	Up-Right Arrow
➡️	Right Arrow
↘️	Down-Right Arrow
⬇️	Down Arrow
↙️	Down-Left Arrow
⬅️	Left Arrow
↖️	Up-Left Arrow
↕️	Up-Down Arrow
↔️	Left-Right Arrow
↩️	Right Arrow Curving Left
↪️	Left Arrow Curving Right
⤴️	Right Arrow Curving Up
⤵️	Right Arrow Curving Down
🔄	Counter-Clockwise Arrows
🔁	Repeat Button
🔝	Top Arrow
🟥	Red Square
🟧	Orange Square
🟨	Yellow Square
🟩	Green Square
🟦	Blue Square
🟪	Purple Square
🟫	Brown Square
⬛	Black Large Square
⬜	White Large Square
◼️	Black Medium Square
◻️	White Medium Square
◾	Black Medium-Small Square
◽	White Medium-Small Square
▪️	Black Small Square
▫️	White Small Square
🔘	Radio Button
🔳	White Square Button
🔲	Black Square Button
🔴	Red Circle
🟠	Orange Circle
🟡	Yellow Circle
🟢	Green Circle
🔵	Blue Circle
🟣	Purple Circle
🟤	Brown Circle
⚫	Black Circle
⚪	White Circle
❤️	Red Heart
🧡	Orange Heart
💛	Yellow Heart
💚	Green Heart
💙	Blue Heart
💜	Purple Heart
🖤	Black Heart
🤍	White Heart
🤎	Brown Heart
💔	Broken Heart
❣️	Heart Exclamation
💕	Two Hearts
💞	Revolving Hearts
💖	Sparkling Heart
💯	100 Hundred Points
💢	Anger Symbol
♻️	Recycle Symbol
❇️	Sparkle
✳️	Eight-Spoked Asterisk
💠	Diamond with a Dot
🆔	ID Button
🆕	NEW Button
🆗	OK Button
🆘	SOS Button
🆙	UP! Button
🆒	COOL Button
🆓	FREE Button
🆖	NG (No Good) Button
🅿️	P Button (Parking)
🎦	Cinema
📶	Antenna Bars
🇦🇫	flag: Afghanistan
🇦🇱	flag: Albania
🇩🇿	flag: Algeria
🇦🇩	flag: Andorra
🇦🇴	flag: Angola
🇦🇬	flag: Antigua & Barbuda
🇦🇷	flag: Argentina
🇦🇲	flag: Armenia
🇦🇺	flag: Australia
🇦🇹	flag: Austria
🇦🇿	flag: Azerbaijan
🇧🇸	flag: Bahamas
🇧🇭	flag: Bahrain
🇧🇩	flag: Bangladesh
🇧🇧	flag: Barbados
🇧🇾	flag: Belarus
🇧🇪	flag: Belgium
🇧🇿	flag: Belize
🇧🇯	flag: Benin
🇧🇹	flag: Bhutan
🇧🇴	flag: Bolivia
🇧🇦	flag: Bosnia & Herzegovina
🇧🇼	flag: Botswana
🇧🇷	flag: Brazil
🇧🇳	flag: Brunei
🇧🇬	flag: Bulgaria
🇧🇫	flag: Burkina Faso
🇧🇮	flag: Burundi
🇨🇻	flag: Cabo Verde
🇰🇭	flag: Cambodia
🇨🇲	flag: Cameroon
🇨🇦	flag: Canada
🇨🇫	flag: Central African Republic
🇹🇩	flag: Chad
🇨🇱	flag: Chile
🇨🇳	flag: China
🇨🇴	flag: Colombia
🇰🇲	flag: Comoros
🇨🇬	flag: Congo (Brazzaville)
🇨🇩	flag: Congo (Kinshasa)
🇨🇷	flag: Costa Rica
🇭🇷	flag: Croatia
🇨🇺	flag: Cuba
🇨🇾	flag: Cyprus
🇨🇿	flag: Czech Republic
🇩🇰	flag: Denmark
🇩🇯	flag: Djibouti
🇩🇲	flag: Dominica
🇩🇴	flag: Dominican Republic
🇪🇨	flag: Ecuador
🇪🇬	flag: Egypt
🇸🇻	flag: El Salvador
🇬🇶	flag: Equatorial Guinea
🇪🇷	flag: Eritrea
🇪🇪	flag: Estonia
🇸🇿	flag: Eswatini
🇪🇹	flag: Ethiopia
🇫🇯	flag: Fiji
🇫🇮	flag: Finland
🇫🇷	flag: France
🇬🇦	flag: Gabon
🇬🇲	flag: Gambia
🇬🇪	flag: Georgia
🇩🇪	flag: Germany
🇬🇭	flag: Ghana
🇬🇷	flag: Greece
🇬🇹	flag: Guatemala
🇬🇳	flag: Guinea
🇬🇼	flag: Guinea‑Bissau
🇬🇾	flag: Guyana
🇭🇹	flag: Haiti
🇭🇳	flag: Honduras
🇭🇺	flag: Hungary
🇮🇸	flag: Iceland
🇮🇳	flag: India
🇮🇩	flag: Indonesia
🇮🇷	flag: Iran
🇮🇶	flag: Iraq
🇮🇪	flag: Ireland
🇮🇱	flag: Israel
🇮🇹	flag: Italy
🇯🇲	flag: Jamaica
🇯🇵	flag: Japan
🇯🇴	flag: Jordan
🇰🇿	flag: Kazakhstan
🇰🇪	flag: Kenya
🇰🇮	flag: Kiribati
🇽🇰	flag: Kosovo
🇰🇼	flag: Kuwait
🇰🇬	flag: Kyrgyzstan
🇱🇦	flag: Laos
🇱🇻	flag: Latvia
🇱🇧	flag: Lebanon
🇱🇸	flag: Lesotho
🇱🇷	flag: Liberia
🇱🇾	flag: Libya
🇱🇮	flag: Liechtenstein
🇱🇹	flag: Lithuania
🇱🇺	flag: Luxembourg
🇲🇴	flag: Macau
🇲🇰	flag: North Macedonia
🇲🇬	flag: Madagascar
🇲🇼	flag: Malawi
🇲🇾	flag: Malaysia
🇲🇻	flag: Maldives
🇲🇱	flag: Mali
🇲🇹	flag: Malta
🇲🇭	flag: Marshall Islands
🇲🇶	flag: Martinique
🇲🇷	flag: Mauritania
🇲🇺	flag: Mauritius
🇾🇹	flag: Mayotte
🇲🇽	flag: Mexico
🇫🇲	flag: Micronesia
🇲🇩	flag: Moldova
🇲🇨	flag: Monaco
🇲🇳	flag: Mongolia
🇲🇪	flag: Montenegro
🇲🇸	flag: Montserrat
🇲🇦	flag: Morocco
🇲🇿	flag: Mozambique
🇳🇦	flag: Namibia
🇳🇷	flag: Nauru
🇳🇵	flag: Nepal
🇳🇱	flag: Netherlands
🇳🇨	flag: New Caledonia
🇳🇿	flag: New Zealand
🇳🇮	flag: Nicaragua
🇳🇪	flag: Niger
🇳🇬	flag: Nigeria
🇳🇺	flag: Niue
🇳🇫	flag: Norfolk Island
🇲🇵	flag: Northern Mariana Islands
🇰🇵	flag: North Korea
🇳🇴	flag: Norway
🇴🇲	flag: Oman
🇵🇰	flag: Pakistan
🇵🇼	flag: Palau
🇵🇸	flag: Palestine
🇵🇦	flag: Panama
🇵🇬	flag: Papua New Guinea
🇵🇾	flag: Paraguay
🇵🇪	flag: Peru
🇵🇭	flag: Philippines
🇵🇱	flag: Poland
🇵🇹	flag: Portugal
🇵🇷	flag: Puerto Rico
🇶🇦	flag: Qatar
🇷🇴	flag: Romania
🇷🇺	flag: Russia
🇷🇼	flag: Rwanda
🇼🇸	flag: Samoa
🇸🇲	flag: San Marino
🇸🇹	flag: São Tomé & Príncipe
🇸🇦	flag: Saudi Arabia
🇸🇳	flag: Senegal
🇷🇸	flag: Serbia
🇸🇨	flag: Seychelles
🇸🇱	flag: Sierra Leone
🇸🇬	flag: Singapore
🇸🇽	flag: Sint Maarten
🇸🇰	flag: Slovakia
🇸🇮	flag: Slovenia
🇸🇧	flag: Solomon Islands
🇸🇴	flag: Somalia
🇿🇦	flag: South Africa
🇰🇷	flag: South Korea
🇸🇸	flag: South Sudan
🇪🇸	flag: Spain
🇱🇰	flag: Sri Lanka
🇸🇩	flag: Sudan
🇸🇷	flag: Suriname
🇸🇿	flag: Eswatini
🇸🇪	flag: Sweden
🇨🇭	flag: Switzerland
🇸🇾	flag: Syria
🇹🇼	flag: Taiwan
🇹🇯	flag: Tajikistan
🇹🇿	flag: Tanzania
🇹🇭	flag: Thailand
🇹🇱	flag: Timor‑Leste
🇹🇬	flag: Togo
🇹🇰	flag: Tokelau
🇹🇴	flag: Tonga
🇹🇹	flag: Trinidad & Tobago
🇹🇳	flag: Tunisia
🇹🇷	flag: Turkey
🇹🇲	flag: Turkmenistan
🇹🇨	flag: Turks & Caicos Islands
🇹🇻	flag: Tuvalu
🇺🇬	flag: Uganda
🇺🇦	flag: Ukraine
🇦🇪	flag: United Arab Emirates
🇬🇧	flag: United Kingdom
🇺🇸	flag: United States
🇺🇾	flag: Uruguay
🇺🇿	flag: Uzbekistan
🇻🇺	flag: Vanuatu
🇻🇦	flag: Vatican City
🇻🇪	flag: Venezuela
🇻🇳	flag: Vietnam
🇼🇫	flag: Wallis & Futuna
🇾🇪	flag: Yemen
🇿🇲	flag: Zambia
🇿🇼	flag: Zimbabwe
🏴󠁧󠁢󠁥󠁮󠁧󠁿	 flag: England
🏴󠁧󠁢󠁳󠁣󠁴󠁿	 flag: Scotland
🏴󠁧󠁢󠁷󠁬󠁳󠁿	 flag: Wales
🏳️‍🌈	flag: Rainbow Pride LGBTQ+ Flag
🏳️‍⚧️	flag: Transgender Flag
🇺🇳	flag: United Nations
🇪🇺	flag: European Union
🏴‍☠️	flag: Pirate Flag
🏁	flag: Chequered Flag
🚩	flag: Triangular Flag
🎌	flag: Crossed Flags
🏴	flag: Black Flag
🏳️	flag: White Flag
🇭🇰	flag: Hong Kong
🇲🇴	flag: Macau
🇵🇷	flag: Puerto Rico
🇬🇺	flag: Guam
🇦🇸	flag: American Samoa
🇻🇬	flag: British Virgin Islands
🇮🇴	flag: British Indian Ocean Territory
🇫🇮	flag: Aland Islands
🇬🇫	flag: French Guiana
🇬🇵	flag: Guadeloupe
🇲🇶	flag: Martinique
🇷🇪	flag: Reunion
🇾🇹	flag: Mayotte
🇳🇫	flag: Norfolk Island
🇨🇽	flag: Christmas Island
🇨🇨	flag: Cocos (Keeling) Islands
🇫🇴	flag: Faroe Islands
🇬🇱	flag: Greenland
🇦🇽	flag: Åland Islands
🇧🇻	flag: Bouvet Island
🇸🇯	flag: Svalbard & Jan Mayen
🇹🇫	flag: French Southern Territories
🇼🇫	flag: Wallis & Futuna
🇵🇲	flag: Saint Pierre & Miquelon
🇸🇭	flag: Saint Helena
🇬🇸	flag: South Georgia & South Sandwich Islands
🇫🇰	flag: Falkland Islands
🇦🇮	flag: Anguilla
🇲🇸	flag: Montserrat
🇹🇨	flag: Turks & Caicos Islands
🇰🇾	flag: Cayman Islands
🇧🇲	flag: Bermuda
🇻🇮	flag: U.S. Virgin Islands
🇺🇲	flag: U.S. Outlying Islands
🇲🇵	flag: Northern Mariana Islands
🇵🇼	flag: Palau (Compact of Free Association)
🇲🇭	flag: Marshall Islands (Compact of Free Association)
🇫🇲	flag: Micronesia (Compact of Free Association)
🇦🇶	flag: Antarctica
EOF

# ----------------------------------------------------------------------
# 3. Process Emojis (Inject Tones)
# ----------------------------------------------------------------------
PROCESSED_DATA=$(echo "$EMOJI_DATA" | while IFS=$'\t' read -r emoji desc; do
    case "$emoji" in
        # PROFESSIONAL: Inject Tone before the Joiner (e.g., 👨 + TONE + ZWJ + 🎨)
        # When adding to this list, use the non-binary form to cover all three forms.
        "👨"*|"👩"*|"🧑"*|"🚣"*|"🏃"*|"🚶"*|"🏊"*| \
        "🏋"*|"🧗"*|"🧖"*|"🚴"*|"🚵"*|"🧘"*|"⛹️"*| \
        "🏌️"*|"🏄"*|"🤺"*|"🤹"*|"🕴️"*|"🤽"*|"🤾"*| \
        "👯"*|"⛷️"*|"💃"*|"🕺"*|"🧏"*|"👳"*|"🙎"*| \
        "🙍"*|"🙅"*|"🙆"*|"💁"*|"🙋"*|"🙇"*|"🤦"*|"🤷"*)
            BASE_CHAR="${emoji:0:1}"
            REST_CHAR="${emoji:1}"
            if [ "$MULTI_TONE" = true ]; then
            printf "%s%b%s\t%s\n%s%b%s\t%s\n%s%b%s\t%s\n%s%b%s\t%s\n%s%b%s\t%s\n%s%b%s\t%s\n" \
                "$BASE_CHAR" "$TONE1" "$REST_CHAR" "$desc" \
                "$BASE_CHAR" "$TONE2" "$REST_CHAR" "$desc" \
                "$BASE_CHAR" "$TONE3" "$REST_CHAR" "$desc" \
                "$BASE_CHAR" "$TONE4" "$REST_CHAR" "$desc" \
                "$BASE_CHAR" "$TONE5" "$REST_CHAR" "$desc" \
                "$BASE_CHAR" " " "$REST_CHAR" "$desc"
            else
            printf "%s%b%s\t%s\n" "$BASE_CHAR" "$TONE1" "$REST_CHAR" "$desc"
            fi
            ;;
        # STANDARD HUMAN: Simple suffixing
        "🖖"|"🤘"|"🤟"|"🤞"|"✋"|"✊"|"👏"|"🤚"| \
        "✋️"|"🙌"|"🤙"|"👐"|"🤝"|"👍"|"👎"|"👊"| \
        "👌"|"👋"|"💪"|"🤳"|"👂"|"👃"|"🤲"|"🖐"| \
        "✌️"|"🤏"|"🤌"|"👌"|"🫸"|"🫷"|"🫴"|"🫳"| \
        "🫲"|"🫱"|"🫵"|"👊"|"🤛"|"🤜"|"🫶"|"🫰"| \
        "👈"|"👉"|"👆"|"☝️"|"👇"|"🖕"|"🙏"|"✍️"| \
        "💅"|"🦵"|"🦶"|"🦻"|"👶"|"🧒"|"👦"|"👧"| \
        "🧑"|"👱"|"👨"|"🧔"|"🧔‍♂️"|"🧔‍♀️"|"👨‍🦰"|"👨‍🦱"| \
        "👨‍🦳"|"👨‍🦲"|"👩"|"👩‍🦰"|"🧑‍🦰"|"👩‍🦱"|"🧑‍🦱"|"👩‍🦳"| \
        "🧑‍🦳"|"👩‍🦲"|"🧑‍🦲"|"👱‍♀️"|"👱‍♂️"|"🧓"|"👴"|"👵"| \
        "👲"|"🧕"|"🤰"|"🫃"|"🫄"|"👼")
            if [ "$MULTI_TONE" = true ]; then
            printf "%s%b\t%s\n%s%b\t%s\n%s%b\t%s\n%s%b\t%s\n%s%b\t%s\n%s%b\t%s\n" \
                "$emoji" "$TONE1" "$desc" \
                "$emoji" "$TONE2" "$desc" \
                "$emoji" "$TONE3" "$desc" \
                "$emoji" "$TONE4" "$desc" \
                "$emoji" "$TONE5" "$desc" \
                "$emoji" " " "$desc" \

            else
            printf "%s%b\t%s\n" "$emoji" "$TONE1" "$desc"
            fi
            ;;
        # DEFAULT: All non-human/non-tonable emojis
        *)
            printf "%s\t%s\n" "$emoji" "$desc"
            ;;
    esac
done)

# ----------------------------------------------------------------------
# 4. Run fzf with Swatch Indicator
# ----------------------------------------------------------------------
PROMPT_STR=$(printf "Pick an emoji%b> ")

SELECTED=$(echo "$PROCESSED_DATA" |
    fzf --ansi \
        --prompt="$PROMPT_STR" \
        --height=40% \
        --layout=reverse \
        --delimiter=$'\t' \
        --nth=2 \
        --ignore-case \
        --exact)

# ----------------------------------------------------------------------
# 5. Output and Clipboard
# ----------------------------------------------------------------------
if [[ -n $SELECTED ]]; then
    EMOJI=$(cut -f1 <<<"$SELECTED")

    if command -v pbcopy >/dev/null 2>&1; then
        printf "%s" "$EMOJI" | pbcopy
    elif command -v xclip >/dev/null 2>&1; then
        printf "%s" "$EMOJI" | xclip -selection clipboard
    fi

fi

# ----------------------------------------------------------------------
# 3. Output the chosen emoji
# ----------------------------------------------------------------------
if [[ -n $SELECTED ]]; then
    EMOJI=$(cut -f1 <<<"$SELECTED")

    # Clipboard handling (Linux/macOS)
    if command -v xclip >/dev/null 2>&1; then
        printf "%s" "$EMOJI" | xclip -selection clipboard
    elif command -v xsel >/dev/null 2>&1; then
        printf "%s" "$EMOJI" | xsel --clipboard --input
    elif command -v pbcopy >/dev/null 2>&1; then
        printf "%s" "$EMOJI" | pbcopy
    fi

    printf "%s\n" "$EMOJI"
fi
