#!/usr/bin/env bash


FOLDER=${PWD:-$1}

if [[ -d "${FOLDER}/.git" ]]; then
    HAS_GIT=true
else
    echo "Not a .git folder, exiting..."
    exit 1
fi

git -C "$FOLDER" branch --all \
  | sed -E 's/^[* ]+//' \
  | sed 's|remotes/||' \
  | grep -v '^origin/HEAD' \
  | fzf \
      --layout=reverse \
      --no-input \
      --border \
      --preview-window=right:70%:wrap \
      --preview \
'git log \
    --graph \
    --decorate \
    --color=always \
    --pretty=format:"%C(bold blue)%h%C(reset) -%C(bold yellow)%d%C(reset) %C(green)%cr%C(reset) %C(bold)%s%C(reset) %C(dim)%an%C(reset)" \
    -n 15 {}' \
  | tr -d '\n' \
  | xargs -r git checkout
