#!/usr/bin/env bash

# Description: Show file-info in a human ready format


FILENAME=$1
HAS_GIT=false
SHOW_GIT=true

print_usage() {
    echo "Usage:  file-info [FILE]"
}

source string-tools

if [[ ! -f "$FILENAME" ]]; then
    echo ""
    echo -e "${RED}Error: file not found or set.${RESET} $FILENAME"
    echo ""
    print_usage
    exit 1
fi


# Basic Info
# Absolute path
ABS_PATH=$(realpath "$FILENAME")
FOLDER=$(dirname "$ABS_PATH")
if [[ -d "${FOLDER}/.git" ]]; then
    HAS_GIT=true
fi
# Kind
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_KIND=$(mdls -name kMDItemKind "$ABS_PATH" | awk -F'"' '{print $2}')
else
    FILE_KIND=$(xdg-mime query filetype "$ABS_PATH")
fi

# Apparent size
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_SIZE=$(ls -lh "$ABS_PATH" | awk '{print $5}')
else
    FILE_SIZE=$(du -shA "$ABS_PATH" | awk '{print $1}')
fi

# Created Date
if [[ "$HAS_GIT" == false ]]; then
    if [[ $(uname -s) == "Darwin" ]]; then
        FILE_CREATED_DATE=$(stat -f "%SB" -t "%Y-%m-%d %H:%M:%S" "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -f "%Y-%m-%d %H:%M:%S" -j "{}" "+%A, %B %d, %Y at %I:%M %p")
    else
        FILE_CREATED_DATE=$(stat -c %w "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -d "{}" "+%A, %B %d, %Y at %I:%M %p")
    fi
else
    if [[ $(uname -s) == "Darwin" ]]; then
        FILE_CREATED_DATE=$(git log --follow --format=%at --reverse "$ABS_PATH" | head -1 | xargs -I {} date -r {} "+%A, %B %d, %Y at %I:%M %p")
    else
        FILE_CREATED_DATE=$(git log --diff-filter=A --format=%ad --date=iso -- README.md | xargs -I {} date -d {} +"%A, %B %-d, %Y at %-I:%M %p")
    fi
fi

# Modified Date - Doesn't use git, because we want the last modification of the file, even if it is not committed
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_MODIFIED_DATE=$(stat -f "%SB" -t "%Y-%m-%d %H:%M:%S" "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -f "%Y-%m-%d %H:%M:%S" -j "{}" "+%A, %B %d, %Y at %I:%M %p")
else
    FILE_MODIFIED_DATE=$(stat -c %y "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -d "{}" "+%A, %B %d, %Y at %I:%M %p")
fi

# PDF info
if [[ "$FILE_KIND" == *"pdf"* || "$FILE_KIND" == *"PDF"* ]]; then

    # Title
    if [[ $(uname -s) == "Darwin" ]]; then
        PDF_TITLE=$(mdls -name kMDItemTitle "$ABS_PATH" | awk -F'"' '{print $2}')
    else
        PDF_TITLE=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Title/ {print $2}')
    fi

    # Authors
    if [[ $(uname -s) == "Darwin" ]]; then
        PDF_AUTHORS=$(mdls -name kMDItemAuthors "$ABS_PATH" | awk -F'"' '$2 != "" { v=$2; print (length(v)>65 ? substr(v,1,65)"..." : v) }')
    else
        PDF_AUTHORS=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Creator/ {val=$2; print (length(val) > 65) ? substr(val,1,65) "..." : val}')
        if [[ $PDF_AUTHORS == "" ]]; then
            PDF_AUTHORS=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Author/ {val=$2; print (length(val) > 65) ? substr(val,1,65) "..." : val}')
        fi
    fi

    # Pages
    PDF_PAGES=$(pdfinfo "$ABS_PATH" | grep "Pages:" | awk '{print $2}')
    # Creation Date
    PDF_CREATION_DATE=$(pdfinfo "$ABS_PATH" | grep "CreationDate:" | awk '{sub(/^[^[:space:]]+[[:space:]]+/, ""); print}')
    # Modified Date
    PDF_MODIFIED_DATE=$(pdfinfo "$ABS_PATH" | grep "ModDate:" | awk '{sub(/^[^[:space:]]+[[:space:]]+/, ""); print}')
    # Resolution
    PDF_RESOLUTION=$(pdfinfo "$ABS_PATH" | grep "Page size:" | awk '{sub(/^[^[:space:]]+[[:space:]]+/, ""); print}')
    # Orientation (use resolution numbers)
    PDF_ORIENTATION=$(echo $PDF_RESOLUTION | awk '{if ($1 > $3) print "Landscape"; else print "Portrait"}')
    # Version
    PDF_VERSION=$(pdfinfo "$ABS_PATH" | grep "PDF version:" | awk '{print $3}')
fi



# Image file info
if [[ ${FILE_KIND,,} == *"image"* ]]; then

    # Resolution and Orientation
    if [[ $(uname -s) == "Darwin" ]]; then
        IMG_RESOLUTION=$(mdls --name kMDItemPixelWidth --name kMDItemPixelHeight "$ABS_PATH" | awk -F'=' '{
            gsub(/ /,"",$2);
            val[NR]=$2
        } END {
            print val[2] "x" val[1]
        }')
    else
        IMG_RESOLUTION=$(identify -format "%wx%h" "$ABS_PATH")
    fi
    IMG_ORIENTATION=$(echo "$IMG_RESOLUTION" | awk -F'x' '{if ($1 > $2) print "Landscape"; else if ($1 < $2) print "Portrait"; else print "Square"}')
fi

# Output header
echo -e "\n${BOLD}${BLUE}📄 File Information${RESET}"
print_kv "Location" "$ABS_PATH"
print_kv "Kind" "$FILE_KIND"
print_kv "Size" "$FILE_SIZE"
print_kv "Created" "$FILE_CREATED_DATE"
print_kv "Modified" "$FILE_MODIFIED_DATE"
permissions_calc $ABS_PATH

if [[ "$FILE_KIND" == *"pdf"* || "$FILE_KIND" == *"PDF"* ]]; then
echo -e "\n${BOLD}${BLUE}📄 PDF Information${RESET}"
print_kv "Title" "$PDF_TITLE"
print_kv "Author" "${PDF_AUTHORS}"
print_kv "Pages" "${PDF_PAGES}"
print_kv "PDF Creation Date" "$PDF_CREATION_DATE"
print_kv "PDF Modified Date" "$PDF_MODIFIED_DATE"
print_kv "Orientation" "$PDF_ORIENTATION"
print_kv "PDF Version" "$PDF_VERSION"
fi

if [[ ${FILE_KIND,,} == *"image"* ]]; then
echo -e "\n${BOLD}${BLUE}🖼️ Image Information${RESET}"
print_kv "Image Resolution" "$IMG_RESOLUTION"
print_kv "Image Orientation" "$IMG_ORIENTATION"
fi

if [[ ${FILE_KIND,,} == *"text"* ]] || [[ ${FILE_KIND,,} == *"markdown"* ]]; then
    text_file_stats
fi

if [[ "$SHOW_GIT" == true ]] && [[ "$HAS_GIT" == true ]]; then
    source git-info-blob file
fi
