#!/usr/bin/env bash

FILENAME=$1
HAS_GIT=false

print_usage() {
    echo "Usage:  file-info [FILE]"
}

section_header() {
    echo -e "\n${BOLD}${CYAN}→${RESET} ${BOLD}$1${RESET}"
}

# Helper function for key-value pairs
print_kv() {
    echo -e $3 "${BLUE}$(printf '%-20.20s' "$1")${RESET} ${WHITE}${2}${RESET}"
}

source set-colors

if [[ ! -f "$FILENAME" ]]; then
    echo ""
    echo -e "${RED}Error: file not found or set.${RESET} $FILENAME"
    echo ""
    print_usage
    exit 1
fi


# Basic Info
# Absolute path
ABS_PATH=$(realpath "$FILENAME")
FOLDER=$(dirname "$ABS_PATH")
if [[ -d "${FOLDER}/.git" ]]; then
    HAS_GIT=true
fi
# Kind
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_KIND=$(mdls -name kMDItemKind "$ABS_PATH" | awk -F'"' '{print $2}')
else
    FILE_KIND=$(xdg-mime query filetype "$ABS_PATH")
fi

# Apparent size
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_SIZE=$(ls -lh "$ABS_PATH" | awk '{print $5}')
else
    FILE_SIZE=$(du -shA "$ABS_PATH" | awk '{print $1}')
fi

# Created Date
if [[ "$HAS_GIT" == false ]]; then
    if [[ $(uname -s) == "Darwin" ]]; then
        FILE_CREATED_DATE=$(mdls -name kMDItemFSCreationDate "$ABS_PATH" | awk '{print $3, $4}' | xargs -I {} date -f "%Y-%m-%d %H:%M:%S" -j "{}" "+%A, %B %d, %Y at %I:%M %p")
    else
        FILE_CREATED_DATE=$(stat -c %w "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -d "{}" "+%A, %B %d, %Y at %I:%M %p")
    fi
else
    FILE_CREATED_DATE=$(git log --follow --format=%at --reverse "$ABS_PATH" | head -1 | xargs -I {} date -r {} "+%A, %B %d, %Y at %I:%M %p")
fi

# Modified Date - Doesn't use git, because we want the last modification of the file, even if it is not committed
if [[ $(uname -s) == "Darwin" ]]; then
    FILE_MODIFIED_DATE=$(mdls -name kMDItemFSContentChangeDate "$ABS_PATH" | awk '{print $3, $4, $5}' | xargs -I {} date -f "%Y-%m-%d %H:%M:%S %z" -j "{}" "+%A, %B %d, %Y at %I:%M %p")
else
    FILE_MODIFIED_DATE=$(stat -c %y "$ABS_PATH" | awk '{print $1, $2}' | xargs -I {} date -d "{}" "+%A, %B %d, %Y at %I:%M %p")
fi

# Permissions
PERMS=$(ls -ld "$FILENAME" | awk '{print $1}')
# Get the numeric version (OS-agnostic check)
if [[ $(uname -s) == "Darwin" ]]; then
    NUMERIC_PERMS=$(stat -f "%Lp" "$FILENAME")
else
    NUMERIC_PERMS=$(stat -c "%a" "$FILENAME")
fi

# Helper function to format the 'rwx' triplets
parse_bit() {
    [[ $1 == "$2" ]] && echo "  ●  " || echo "  ○  "
}
# Extract triplets
U_R=$(parse_bit "${PERMS:1:1}" "r")
U_W=$(parse_bit "${PERMS:2:1}" "w")
U_X=$(parse_bit "${PERMS:3:1}" "x")

G_R=$(parse_bit "${PERMS:4:1}" "r")
G_W=$(parse_bit "${PERMS:5:1}" "w")
G_X=$(parse_bit "${PERMS:6:1}" "x")

O_R=$(parse_bit "${PERMS:7:1}" "r")
O_W=$(parse_bit "${PERMS:8:1}" "w")
O_X=$(parse_bit "${PERMS:9:1}" "x")



# PDF info
if [[ "$FILE_KIND" == *"pdf"* || "$FILE_KIND" == *"PDF"* ]]; then

# Title
if [[ $(uname -s) == "Darwin" ]]; then
    PDF_TITLE=$(mdls -name kMDItemTitle "$ABS_PATH" | awk -F'"' '{print $2}')
else
    PDF_TITLE=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Title/ {print $2}')
fi

# Authors
if [[ $(uname -s) == "Darwin" ]]; then
    PDF_AUTHORS=$(mdls -name kMDItemAuthors "$ABS_PATH" | awk -F'"' '$2 != "" { v=$2; print (length(v)>65 ? substr(v,1,65)"..." : v) }')
else
    PDF_AUTHORS=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Creator/ {val=$2; print (length(val) > 65) ? substr(val,1,65) "..." : val}')
    if [[ $PDF_AUTHORS == "" ]]; then
        PDF_AUTHORS=$(pdfinfo "$ABS_PATH" | awk -F': +' '/Author/ {val=$2; print (length(val) > 65) ? substr(val,1,65) "..." : val}')
    fi
fi

# Pages
# Resolution
# Orientation (use resolution numbers)
# Version
fi



# Image file info
# Resolution
# Orientation (use resolution numbers)

# Text file info
# Number of characters
# Number of words
# Number of lines
# Encoding format

# Git info (if applicable)


# Output header
echo -e "\n${BOLD}${BLUE}📄 File Information${RESET}"
print_kv "Location" "$ABS_PATH"
print_kv "Kind" "$FILE_KIND"
print_kv "Size" "$FILE_SIZE"
print_kv "Created" "$FILE_CREATED_DATE"
print_kv "Modified" "$FILE_MODIFIED_DATE"
print_kv "Permissions ($NUMERIC_PERMS)" "" "-n"
echo -e "┏━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━┓"
echo -e "\t\t     ┃ Entity ┃ Read  ┃ Write ┃ Execute ┃"
echo -e "\t\t     ┣━━━━━━━━╋━━━━━━━╋━━━━━━━╋━━━━━━━━━┫"
printf "\t\t     ┃ Owner  ┃%s  ┃%s  ┃%s    ┃\n" "$U_R" "$U_W" "$U_X"
echo -e "\t\t     ┣━━━━━━━━╋━━━━━━━╋━━━━━━━╋━━━━━━━━━┫"
printf "\t\t     ┃ Group  ┃%s  ┃%s  ┃%s    ┃\n" "$G_R" "$G_W" "$G_X"
echo -e "\t\t     ┣━━━━━━━━╋━━━━━━━╋━━━━━━━╋━━━━━━━━━┫"
printf "\t\t     ┃ Others ┃%s  ┃%s  ┃%s    ┃\n" "$O_R" "$O_W" "$O_X"
echo -e "\t\t     ┗━━━━━━━━┻━━━━━━━┻━━━━━━━┻━━━━━━━━━┛"

if [[ "$FILE_KIND" == *"pdf"* || "$FILE_KIND" == *"PDF"* ]]; then
echo -e "\n${BOLD}${BLUE}📄 PDF Information${RESET}"
print_kv "Title" "$PDF_TITLE"
print_kv "Author" "${PDF_AUTHORS}"
fi