#!/usr/bin/env bash

if [[ $(uname -s) == "Darwin" ]]; then
    find-files -q | fzf-prev "osascript -e 'tell application \"Finder\" to set desktop picture to POSIX file \"{}\"'"
  elif [[ $(uname -s) == "Linux" ]]; then
    find-files | fzf-prev "${CORE_COMMAND} {}"
fi
